Models/Article.cs
using System.ComponentModel.DataAnnotations;
using System.Diagnostics.CodeAnalysis;

namespace WebApplication1.Models
{
    public class Article : BaseCms
    {
        public List<Category>? Categories { get; set; }
        public List<Image>? Images { get; set; }
    }
}

Controllers/CmsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using WebApplication1.Models;
using WebApplication1.Models.Dto;
using WebApplication1.Services;

namespace WebApplication1.Controllers
{
    public class CmsController : Controller
    {
        FileService _FileService;
        CmsService _CmsService;

        public CmsController(FileService fileService, CmsService cmsService)
        {
            _FileService = fileService;
            _CmsService = cmsService;
        }
        public IActionResult Index()
        {
            PageModel pageModel = _CmsService.GetPageData();
            return View(pageModel);
        }
        [Authorize]
        public IActionResult Category(int categoryId)
        {
            PageModel pageModel = _CmsService.GetPageData();
            Category selectedCategory = _CmsService.GetCategoryById(categoryId);
            pageModel.SelectedCategory = selectedCategory;
            return View("/Views/Cms/Category/Category.cshtml", pageModel);
        }
        [Authorize]
        [HttpPost]
        public IActionResult CategoryEdit(Category editedCategory)
        {
            _CmsService.UpdateCategory(editedCategory);
            PageModel pageModel = _CmsService.GetPageData();
            pageModel.SelectedCategory = editedCategory;
            return RedirectToAction("Category", new { categoryId = editedCategory.Id });
        }
        [Authorize]
        public IActionResult CategoryAdd(int categoryId)
        {
            PageModel pageModel = _CmsService.GetPageData();
            Category category = new Category();
            category.ParentId = categoryId;
            pageModel.SelectedCategory = category;
            ViewBag.IsForAdd = true;
            return View("/Views/Cms/Category/Category.cshtml", pageModel);
        }
        [Authorize]
        [HttpPost]
        public IActionResult CategoryAdd(Category addedCategory)
        {
            addedCategory.Type = "category";
            _CmsService.CreateCategory(addedCategory);
            PageModel pageModel = _CmsService.GetPageData();
            pageModel.SelectedCategory = addedCategory;
            return RedirectToAction("Category", new { categoryId = addedCategory.Id });
        }
        [Authorize]
        public IActionResult ArticleEdit(int articleId)
        {
            PageModel pageModel = _CmsService.GetPageData();
            Article article = _CmsService.GetArticleById(articleId);
            pageModel.SelectedArticle = ArticleDto.ToArticleDto(article);

            foreach (Category category in pageModel.Categories)
            {
                pageModel.SelectedArticle.AvailableCategoriesList.Add(new SelectListItem() { Selected = false, Text = category.Title, Value = category.Id.ToString() });
            }
            return View("/Views/Cms/Article/ArticleEditLayout.cshtml", pageModel);
        }
        [HttpPost]
        [Authorize]
        public IActionResult ArticleEdit(ArticleDto articleDto)
        {
            PageModel pageModel = _CmsService.GetPageData();
            Article editedArticle = pageModel.Articles.FirstOrDefault(x => x.Id == articleDto.Id);
            Article article = ArticleDto.ToArticle(articleDto, editedArticle);
            if (int.TryParse(articleDto.AddedCategory, out int addedCategoryId))
            {
                article.Categories.Add(pageModel.Categories.FirstOrDefault(c => c.Id == addedCategoryId));
            }
            if (int.TryParse(articleDto.AddedImage, out int addedImageId))
            {
                article.Images.Add(pageModel.Images.FirstOrDefault(i => i.Id == addedImageId));
            }
            _CmsService.UpdateArticle(editedArticle);
            return RedirectToAction("ArticleList");
        }
        [Authorize]
        public IActionResult ArticleDelete(int articleId)
        {
            _CmsService.DeleteArticleById(articleId);
            return RedirectToAction("ArticleList");
        }
        [Authorize]
        public IActionResult ArticleAdd()
        {
            PageModel pageModel = _CmsService.GetPageData();
            pageModel.SelectedArticle = new ArticleDto();
            foreach (Category category in pageModel.Categories)
            {
                pageModel.SelectedArticle.AvailableCategoriesList.Add(new SelectListItem() { Selected = false, Text = category.Title, Value = category.Id.ToString() });
            }

            return View("/Views/Cms/Article/ArticleAddLayout.cshtml", pageModel);
        }
        [HttpPost]
        [Authorize]
        public IActionResult ArticleAdd(ArticleDto articleDto)
        {
            PageModel pageModel = _CmsService.GetPageData();
            articleDto.Categories.Add(pageModel.Categories.FirstOrDefault(c => c.Id == int.Parse(articleDto.AddedCategory)));
            _CmsService.CreateArticle(articleDto);
            pageModel.Articles.Add(articleDto);
            return View("/Views/Cms/Article/ArticleList.cshtml", pageModel);
        }
        [Authorize]
        public IActionResult ArticleList(int categoryId)
        {
            PageModel pageModel = _CmsService.GetPageData();
            pageModel.SelectedCategory = _CmsService.GetCategoryById(categoryId);
            return View("/Views/Cms/Article/ArticleList.cshtml", pageModel);
        }

        [Authorize]
        public IActionResult Image(int imageId)
        {
            PageModel pageModel = _CmsService.GetPageData();
            return View("/Views/Cms/Image/Image.cshtml", pageModel);
        }

        [Authorize]
        [HttpPost]
        public IActionResult UploadImage([FromForm] IFormFile File)
        {
            _FileService.SaveFile(File);
            return Ok();
        }

        [HttpGet]
        public IActionResult GetImage(string fileName)
        {
            try
            {
                var file = System.IO.File.OpenRead(_FileService.PathBuild(fileName));
                return File(file, "image/jpeg");
            }
            catch (Exception ex)
            {
                return NotFound();
            }
        }
    }
}

Views/Cms/Article/Article.cshtml
@model PageModel
@{
    Layout = "~/Views/Shared/_PageLayout.cshtml";
    <table>
        <tr>
            <th>Title</th>
            <th>Description</th>
            <th>Created on</th>
        </tr>
        @{
            if (Model.SelectedCategory != null)
            {
                foreach (Article article in Model.SelectedCategory.Articles)
                {
                    <tr>
                        <th>@article.Title</th>
                        <th>@article.Description</th>
                        <th>@article.Keywords</th>
                    </tr>
                }
            }
            else
            {
                foreach (Article article in Model.Articles)
                {
                    <tr>
                        <th>@article.Title</th>
                        <th>@article.Description</th>
                        <th>@article.Keywords</th>
                    </tr>
                }
            }
        }
    </table>
}

Views/Cms/Article/ArticleAdd.cshtml
@using WebApplication1.Models.Dto;
@model ArticleDto

<div class="article-page-form-container">
    <div class="header">
    <h3>ARTICLE ADD</h3>
        <a asp-controller="Cms" asp-action="ArticleList" class="close-btn">&#10006;</a>
    </div>
    <form asp-action="ArticleAdd">
        <div asp-validation-summary="ModelOnly"></div>
        <input type="hidden" asp-for="Type" value="article" />
        <div>
            <label asp-for="Title"></label>
            <input class="input" asp-for="Title" />
            <span asp-validation-for="Title"></span>
        </div>
        <div>
            <label asp-for="Description"></label>
            <input class="input" asp-for="Description" />
            <span asp-validation-for="Description"></span>
        </div>
        <div>
            <label asp-for="Keywords"></label>
            <input class="input" asp-for="Keywords" />
            <span asp-validation-for="Keywords"></span>
        </div>
        <div>
            <label asp-for="Code"></label>
            <input class="input" asp-for="Code" />
            <span asp-validation-for="Code"></span>
        </div>
        <div class="list-cat">
            <select asp-items="Model.AvailableCategoriesList" asp-for="AddedCategory">
                <option>Select Category</option>
            </select>
        </div>
        <div class="selected-cats">
            @{
                foreach (Category category in Model.Categories)
                {
                    <span>@category.Title</span>
                }
            }
        </div>
        <div>
            <input id="submit" type="submit" value="Create" />
        </div>
    </form>
</div>

Views/Cms/Article/ArticleAddLayout.cshtml
@model PageModel
@{
    Layout = "~/Views/Shared/_PageLayout.cshtml";
}

<partial name="~/Views/Cms/Article/ArticleAdd.cshtml" model="Model.SelectedArticle" />

Views/Cms/Article/ArticleEdit.cshtml
@using WebApplication1.Models.Dto;
@model ArticleDto

<div class="article-page-form-container">
    <div class="header">
    <h3>ARTICLE EDIT</h3>
        <a asp-controller="Cms" asp-action="ArticleList" class="close-btn">&#10006;</a>
    </div>
    <form asp-action="ArticleEdit">
        <div asp-validation-summary="ModelOnly"></div>
        <input type="hidden" asp-for="Type" value="article" />
        <input type="hidden" asp-for="Id" />
        <input type="hidden" asp-for="Type" />
        <div>
            <label asp-for="Title"></label>
            <input class="input" asp-for="Title" />
            <span asp-validation-for="Title"></span>
        </div>
        <div>
            <label asp-for="Description"></label>
            <input class="input" asp-for="Description" />
            <span asp-validation-for="Description"></span>
        </div>
        <div>
            <label asp-for="Keywords"></label>
            <input class="input" asp-for="Keywords" />
            <span asp-validation-for="Keywords"></span>
        </div>
        <div>
            <label asp-for="Code"></label>
            <input class="input" asp-for="Code" />
            <span asp-validation-for="Code"></span>
        </div>
        <div- class="list-cat">
            <select asp-items="Model.AvailableCategoriesList" asp-for="AddedCategory">
                <option>Select Category</option>
            </select>
        </div->
        <div class="selected-cats">
            @{
                foreach(Category category in Model.Categories)
                {
                    <span>@category.Title</span>
                }
            }
        </div>
        <div>
            <input id="submit" type="submit" value="Create" />
        </div>
    </form>
</div>

Views/Cms/Article/ArticleEditLayout.cshtml
@model PageModel
@{
    Layout = "~/Views/Shared/_PageLayout.cshtml";
}

<partial name="~/Views/Cms/Article/ArticleEdit.cshtml" model="Model.SelectedArticle" />

Views/Cms/Article/ArticleList.cshtml
@model PageModel
@{
    Layout = "~/Views/Shared/_PageLayout.cshtml";
    <div class="add-art-btn">
        <a asp-controller="Cms" asp-action="ArticleAdd">ADD ARTICLE</a>
    </div>
    <table class="article-page">
        <thead>
            <tr>
                <th>TITLE</th>
                <th>DESCRIPTION</th>
                <th>CREATED ON</th>
                <th>EDIT / DELETE</th>
            </tr>
        </thead>
        <tbody class="body">
            @{
                if (Model.SelectedCategory != null)
                {
                    foreach (Article article in Model.SelectedCategory.Articles)
                    {
                        <tr>
                            <th>@article.Title</th>
                            <th>@article.Description</th>
                            <th>@article.Keywords</th>
                            <th><div><a asp-controller="Cms" asp-action="ArticleEdit" asp-route-articleId="@article.Id" class="pencil">&#9998;</a><a class="trash">&#128465;</a></div></th>
                        </tr>
                    }
                }
                else
                {
                    foreach (Article article in Model.Articles)
                    {
                        <tr>
                            <th>@article.Title</th>
                            <th>@article.Description</th>
                            <th>@article.Keywords</th>
                            <th><div class="action-wrapper"><a asp-controller="Cms" asp-action="ArticleEdit" asp-route-articleId="@article.Id" class="pencil">&#9998;</a><a asp-controller="Cms" asp-action="ArticleDelete" asp-route-articleId="@article.Id" class="trash">&#128465;</a></div></th>
                        </tr>
                    }
                }
            }
        </tbody>
    </table>
}